export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_TOP_EARNERS_INIT = "FETCH_TOP_EARNERS_INIT";
export const FETCH_TOP_EARNERS_SUCCESS = "FETCH_TOP_EARNERS_SUCCESS";
export const FETCH_TOP_EARNERS_FAIL = "FETCH_TOP_EARNERS_FAIL";

export const FETCH_PLAYER_DATA_INIT = "FETCH_PLAYER_DATA_INIT";
export const FETCH_PLAYER_DATA_SUCCESS = "FETCH_PLAYER_DATA_SUCCESS";
export const FETCH_PLAYER_DATA_FAIL = "FETCH_PLAYER_DATA_FAIL";

export const SET_CHARGE_REFERENCE = "SET_CHARGE_REFERENCE";

export const SET_COIN_BALANCE_INIT = "SET_COIN_BALANCE_INIT";
export const SET_COIN_BALANCE_SUCCESS = "SET_COIN_BALANCE_SUCCESS";
export const SET_COIN_BALANCE_FAIL = "SET_COIN_BALANCE_FAIL";

export const SET_CASH_BALANCE_INIT = "SET_CASH_BALANCE_INIT";
export const SET_CASH_BALANCE_SUCCESS = "SET_CASH_BALANCE_SUCCESS";
export const SET_CASH_BALANCE_FAIL = "SET_CASH_BALANCE_FAIL";

export const OPEN_SUBMIT_PIN_MODAL = "OPEN_SUBMIT_PIN_MODAL";
export const CLOSE_SUBMIT_PIN_MODAL = "CLOSE_SUBMIT_PIN_MODAL";

export const OPEN_SUBMIT_OTP_MODAL = "OPEN_SUBMIT_OTP_MODAL";
export const CLOSE_SUBMIT_OTP_MODAL = "CLOSE_SUBMIT_OTP_MODAL";

export const OPEN_TRANSACTION_SUCCESS_MODAL = "OPEN_TRANSACTION_SUCCESS_MODAL";
export const CLOSE_TRANSACTION_SUCCESS_MODAL =
  "CLOSE_TRANSACTION_SUCCESS_MODAL";

export const OPEN_TRANSACTION_FAIL_MODAL = "OPEN_TRANSACTION_FAIL_MODAL";
export const CLOSE_TRANSACTION_FAIL_MODAL = "CLOSE_TRANSACTION_FAIL_MODAL";

export const SET_VOUCHER_VALUE = "SET_VOUCHER_VALUE";
