export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_TOP_EARNERS_INIT = "FETCH_TOP_EARNERS_INIT";
export const FETCH_TOP_EARNERS_SUCCESS = "FETCH_TOP_EARNERS_SUCCESS";
export const FETCH_TOP_EARNERS_FAIL = "FETCH_TOP_EARNERS_FAIL";

export const FETCH_PLAYER_DATA_INIT = "FETCH_PLAYER_DATA_INIT";
export const FETCH_PLAYER_DATA_SUCCESS = "FETCH_PLAYER_DATA_SUCCESS";
export const FETCH_PLAYER_DATA_FAIL = "FETCH_PLAYER_DATA_FAIL";
